# Generated by Django 4.2.7 on 2023-12-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cast_price',
            field=models.DecimalField(decimal_places=0, default='', max_digits=12, null=True),
        ),
    ]
