# Generated by Django 5.1.1 on 2024-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('sent', 'Sent'), ('cancel', 'Cancel')], default='new', max_length=20),
        ),
    ]
