# Generated by Django 5.1.1 on 2024-09-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
