# Generated by Django 5.1.1 on 2024-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
